steps:
  - id: Build and Test with Maven
    name: 'gcr.io/cloud-builders/mvn'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mvn test || echo "fail" > /workspace/build-status.txt

  - id: Bubble Maven result
    name: 'gcr.io/cloud-builders/mvn'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ $(< /workspace/build-status.txt) == "fail" ]]; then
          exit 1
        fi
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
timeout: "1600s"