service: springboot-greeting

runtime: java11

instance_class: F2

#system-properties:
  #java.util.logging.config.file: "WEB-INF/logging.properties"
env_variables:
  JAVA_USER_OPTS: -Djava.util.logging.config.file="WEB-INF/logging.properties"
