service: springboot-greeting
runtime: java11
instance_class: F2

system-properties:
  java.util.logging.config.file: "WEB-INF/logging.properties"

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6
  target_concurrent_requests: 100
  min_idle_instances: 1
static_files:
  include_path: "**/webfiles/**.html"